# This file was modelled on the below example:
# https://github.com/binder-examples/python-conda_pip

name: magnetar-env
channels:
  - conda-forge
dependencies:
  - python=2.7.5
  - numpy=1.9.1
  - scipy=0.15.1
  - matplotlib=1.4.2
  - corner
  - emcee
  - pip:
    - twine
    - git+https://github.com/sgibson91/magnetar-propeller/
