# This file was modelled on the below example:
# https://github.com/binder-examples/python-conda_pip

name: magnetar-env
channels:
  - conda-forge
dependencies:
  - python=2.7.*
  - numpy
  - scipy
  - matplotlib
  - corner
  - emcee
  - pip:
    - twine
    - git+https://github.com/sgibson91/magnetar-propeller/
