# This file was modelled on the below example:
# https://github.com/binder-examples/python-conda_pip

name: magnetar-env
channels:
  - conda-forge
dependencies:
  - python=2.7.10
  - numpy=1.8.0
  - scipy=0.13.0
  - matplotlib=1.3.1
  - corner
  - emcee==2.2.1
  - pip:
    - twine
    - git+https://github.com/sgibson91/magnetar-propeller/
