# This file was modelled on the below example:
# https://github.com/binder-examples/python-conda_pip

name: magnetar-env
channels:
  - conda-forge
dependencies:
  - apipkg==1.4
  - atomicwrites==1.1.5
  - attrs==18.1.0
  - bleach==1.5.0
  - certifi==2016.9.26
  - conda==4.3.13
  - configparser==3.5.0
  - cycler==0.10.0
  - Cython==0.28.3
  - decorator==4.3.0
  - emcee==2.1.0
  - entrypoints==0.2.2
  - enum34==1.1.6
  - execnet==1.5.0
  - funcsigs==1.0.2
  - html5lib==0.9999999
  - ipykernel==4.5.2
  - ipython==5.1.0
  - ipywidgets==5.2.2
  - Jinja2==2.9.4
  - jsonschema==2.5.1
  - jupyter==1.0.0
  - MarkupSafe==0.23
  - matplotlib==2.0.0
  - mistune==0.7.3
  - more-itertools==4.2.0
  - mpi4py==2.0.0
  - nbformat==4.2.0
  - nose==1.3.7
  - notebook==4.3.1
  - numpy==1.11.2
  - pandas==0.19.2
  - pandocfilters==1.4.1
  - pathlib2==2.2.0
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - PIL==1.1.7
  - pluggy==0.6.0
  - ptyprocess==0.5.1
  - py==1.5.3
  - pycosat==0.6.1
  - Pygments==2.1.3
  - pyparsing==2.1.10
  - pytest==3.6.1
  - pytest-forked==0.2
  - pytest-xdist==1.22.2
  - python-dateutil==2.6.0
  - pytz==2016.10
  - pyzmq==16.0.2
  - qtconsole==4.2.1
  - requests==2.13.0
  - ruamel.yaml==0.13.14
  - scandir==1.4
  - scipy==0.18.1
  - simplegeneric==0.8.1
  - singledispatch==3.4.0.3
  - six==1.10.0
  - subprocess32==3.2.7
  - terminado==0.6
  - testpath==0.3
  - tornado==4.4.2
  - traitlets==4.3.1
  - typing==3.5.3.0
  - virtualenv==15.1.0
  - wcwidth==0.1.7
  - widgetsnbextension==1.2.6
  - xlrd==1.0.0
  - pip:
    - twine
    - git+https://github.com/sgibson91/magnetar-propeller/
